services:
  - type: web
    name: iqr-backend
    env: node
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer

